"""empty message

Revision ID: 1edabb6d39a4
Revises: 4bc37a6e60fd
Create Date: 2020-11-27 10:48:27.943149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edabb6d39a4'
down_revision = '4bc37a6e60fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'date_of_overnight_stay')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('date_of_overnight_stay', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
